### ISSUE TITLE
大佬可以帮忙加个书源吗

### ISSUE THREAD

**Issue by bxystart** [haitang-blossoms/xiangsesource#2]
网站地址 www.60ks.net

**Comment by haitang-blossoms** [comment]
搞好了，但因为网站搜索无法使用所以仅书库寻书
试试自己动手往源里填入规则
https://github.com/haitang-blossoms/xiangsesource/blob/main/xiangsesource-master/newsource/60ks.json
若无法使用/搞懂那就重新打开issue告知，我发个xbs链接
