### ISSUE TITLE
求大佬帮忙制作一下维基阅读的书源

### ISSUE THREAD

**Issue by zhouxingxing77** [haitang-blossoms/xiangsesource#3]
http://www.wikiyuedu.com/
感激不尽

**Comment by haitang-blossoms** [comment]
搞好了，但大部分书籍在书单搜索里
https://github.com/haitang-blossoms/xiangsesource/blob/main/xiangsesource-master/newsource/wikiyuedu.json
若无法使用/搞懂那就重新打开issue告知，我发个xbs链接

**Comment by Cerimy** [comment]
> 

大佬导入的时候404是咋回事，还有就是JSON的怎么用，谢谢大佬

**Comment by haitang-blossoms** [comment]
> > 
> 
> 大佬导入的时候404是咋回事，还有就是JSON的怎么用，谢谢大佬

尝试导入新的xbs综合链接
