### ISSUE TITLE
https://book.acgmh.net/

### ISSUE THREAD

**Issue by jianglingyuea** [haitang-blossoms/xiangsesource#6]
麻烦大佬实现一下这个源

**Comment by haitang-blossoms** [comment]
香色闺阁暂不支持图片与文字同时显示，你觉得该分两个源一个看文一个看图吗？（分两个源我应该能搞）如果需要为一个源看那找别的大佬看看能不能通过文字转图片实现吧

**Comment by jianglingyuea** [comment]
我没有理解，你是说网站里面小说中既包含文字又包含图片吗？我感觉可以先无视掉图片，绝大部分小说还是纯文字的吧

**Comment by haitang-blossoms** [comment]
oki doki https://github.com/haitang-blossoms/xiangsesource/raw/main/xiangsesource-master/newxbs/bookacgmh.xbs
