### ISSUE TITLE
2.56香色提示无内容

### ISSUE THREAD

**Issue by 2375399351** [haitang-blossoms/xiangsesource#7]
导入https://github.com/haitang-blossoms/xiangsesource/raw/main/xiangsesource-master/readme.md
提示
https://github.com/haitang-blossoms/xiangsesource/tree/main/xiangsesource-master/newxbs无内容
这个咋办
我是开v的，浏览器访问也正常

**Comment by haitang-blossoms** [comment]
可以使用以下解决方法：
- 下载需要导入的xbs文件，并在香色闺阁中打开
- 浏览器访问，复制内容去同步界面导入
