### ISSUE TITLE
BIKA源画质模糊

### ISSUE THREAD

**Issue by Cerimy** [haitang-blossoms/xiangsesource#9]
BIKA源看的东西像打了马赛克，对话看不清

**Comment by haitang-blossoms** [comment]
有没有尝试看看是不是你的网络问题？或者打开原网页看看是不是资源本身的问题？

**Comment by Cerimy** [comment]
> 有没有尝试看看是不是你的网络问题？或者打开原网页看看是不是资源本身的问题？

不是网络问题，源网页资源是高清的，大佬知道怎么回事吗？

**Comment by haitang-blossoms** [comment]
每个线路都模糊吗？我找不到原因，修复不了，请另寻高人吧
